.github/workflow/lint.yaml

- main 브랜치를 제외한 브랜치에 merge할 경우 lint CI 환경 구축

chore: lint CI yaml 파일 추가

---

package-lock.json
package.json
src/components/Common/Button/Button.tsx
src/components/Common/Button/ButtonStyle.ts
src/components/Common/Button/Fab/FabButton.tsx
src/components/Common/Button/Fab/FabButtonStyle.ts
src/components/Common/Button/TextMore/TextMoreButton.tsx
src/components/Common/Button/TextMore/TextMoreButtonStyle.ts
src/components/Common/index.ts
src/pages/index.tsx

feat: button 공통 컴포넌트 추가 작업

---

src/components/Common/Badge/ContainedBadgeStyle.ts
src/components/Common/Badge/OutlinedBadgeStyle.ts
src/styles/styles.d.ts
src/styles/theme.ts

- #5
- 디자인 시스템 컬러 생성
- 현재 피그마에 있는 컬러 시스템 토대로 만들었습니다.

#5 feat: 디자인시스템 컬러 생성

---

.storybook/main.js
package-lock.json
package.json
src/components/Common/Badge/ContainedBadge.stories.tsx
src/components/Common/Badge/ContainedBadgeStyle.ts
src/components/Common/Badge/OutlinedBadge.stories.tsx
src/components/Common/Badge/OutlinedBadge.tsx

- #22
- contained badge, outlined badge 스토리북 적용
- contained badge의 keyword 텍스트 색상 수정
- storybook에서 자꾸 `@styles/theme` module를 import 할 수 없다고 오류가 뜨길래 검색해봤더니 nextjs에서 path alias를 쓸 때 storybook에서 인식을 못하는 오류가 있더라고요.. 아래 링크 보고 해결했습니다 😥
https://github.com/storybookjs/storybook/issues/11639

#22 feat: Badge 디자인 수정 및 스토리북 적용

---

src/components/Common/Forms/Input/Input.stories.tsx
src/components/Common/Forms/Input/Input.tsx
src/components/Common/Forms/TextArea/TextArea.stories.tsx
src/components/Common/Forms/TextArea/TextArea.tsx

- #24
- input과 textarea의 story를 추가했습니다.
-

#24 feat: Form 컴포넌트 스토리북 적용 

---

.dockerignore
Dockerfile

#34 chore: 도커 파일 작성

---

package-lock.json
src/components/ClassDetail/ClassDetailStyle.ts
src/components/ClassDetail/ClassInfo/ClassImages.tsx
src/components/ClassDetail/ClassInfo/ClassInfo.tsx
src/components/ClassDetail/ClassInfo/ClassInfoStyle.ts
src/components/ClassDetail/CoachProfile/CoachProfile.tsx
src/components/ClassDetail/CoachProfile/CoachProfileStyle.ts
src/components/ClassDetail/Guideline/Guideline.tsx
src/components/ClassDetail/Guideline/GuidelineStyle.ts
src/components/ClassDetail/HowToUse/HowToUse.tsx
src/components/ClassDetail/HowToUse/HowToUseStyle.ts
src/components/ClassDetail/index.ts
src/pages/class-detail/[id].tsx

- #17
<p align="center">
</p>
- 
- 텍스트 색상의 경우 Typography component 수정하신 뒤 수정 할 예정입니다.

#17 feat: 클래스 상세 페이지 레이아웃

---

src/components/Common/Badge/ContainedBadge.tsx
src/components/Common/Badge/ContainedBadgeStyle.ts
src/components/Common/Badge/OutlinedBadge.tsx
src/components/Common/Badge/OutlinedBadgeStyle.ts

- #39
- Badge component의 텍스트 스타일을  typography 컴포넌트로 변경
-

#39 style: Badge 컴포넌트 텍스트 스타일 수정

---

Dockerfile

- #45
- 요청하신대로 빌드한 파일만 배포되게끔 수정했습니다. 이전에 7MB를 받았던 resource 크기를 900kB 로 줄였습니다!
-

#45 chore: docker 이미지 경량화

---

src/styles/font.ts

- #53 
- 웹 로드 되는 동안 텍스트 유지를 위해 폰트 최적화 코드 추가
- N/A

#53 feat: 폰트 최적화

---

Dockerfile

- #57 
- 의존성 모듈 강제 설치 명령어 추가
- N/A

#57 feat: 도커 파일 RUN 명령어 수정

---

src/components/Common/Forms/TextArea/TextArea.tsx
src/pages/review/[idx].tsx

- #60
- text area props를 필수가 아닌 선택으로 수정
-

#60 fix: 리뷰 페이지 배포 오류 수정 

---

src/components/Common/SearchBar/SearchBarStyle.ts
src/components/Home/LectureCard/LectureCard.tsx
src/components/Home/LectureCard/LectureCardStyle.ts
src/components/Home/LectureCard/LoadingCard.tsx
src/components/Home/LectureCard/LoadingCardStyle.ts
src/components/Home/LectureList/LoadingList.tsx
src/components/Home/SearchModal/SearchModal.tsx
src/components/Home/index.ts
src/pages/category/index.tsx
src/pages/index.tsx

#56 feat: 클래스 목록 스켈레톤 UI 적용

---

src/api/index.ts
src/hooks/review/useRegisterReview.ts
src/pages/review/[idx].tsx
src/types/review.ts

- #64
- 사용자가 코치에게 리뷰를 작성하는 기능 구현
- 리액트쿼리에 익숙지는 않아서,, 많은 피드백 부탁드립니다 🙇‍♀️

#64 feat: 리뷰 작성 기능

---

next.config.js
package-lock.json
package.json
src/components/Home/LectureCard/LectureCard.tsx
src/components/Home/LectureCard/LectureCardStyle.ts
src/components/Home/LectureCard/LoadingCard.tsx
src/components/Home/LectureCard/LoadingCardStyle.ts
src/components/Home/LectureList/LectureList.tsx
src/types/lectureInfo.ts

- #74 
- 클래스 목록 API에 태그 및 이미지 값이 추가됨에 따라 해당 데이터 컴포넌트에 적용
- N/A

#74 feat: 클래스 목록에 태그 및 이미지 값 적용

---

package-lock.json
package.json
src/api/index.ts
src/components/LectureDetail/CoachProfile/CoachProfile.tsx
src/components/LectureDetail/LectureInfo/LectureImages.tsx
src/components/LectureDetail/LectureInfo/LectureInfo.tsx
src/hooks/lecture/useLectureDetail.ts
src/pages/lecture-detail/[id].tsx
src/react-query/keys.ts
src/types/lectureDetail.ts
src/utils/formatSchedule.ts
src/utils/index.ts

- #63
- 클래스 상세 페이지 api 연동
- dayjs 모듈 설치해서 가능한 시간 날짜 포맷팅 (utils 아래 formatSchedule 파일 생성)
-

#63 feat: 클래스 상세 페이지 API 연동

---

jest.config.js
src/__tests__/category/LectureCategory.test.tsx
src/__tests__/category/useInfiniteLecture.test.tsx
src/components/Home/Category/Category.tsx
src/components/Home/LectureCard/LoadingCard.tsx
src/mocks/handlers.js
src/mocks/mockData/lectureInfo.js
src/pages/lecture-category/[id].tsx
src/test-utils/index.tsx

- #80 
- 카테고리 별 클래스 데이터 조회 시 성능 개선을 위한 SSR 적용 (SSR 테스트 완료)
- 카테고리 별 데이터 api 및 UI 테스트 코드 작성
- N/A

#80 feat: 클래스 별 카테고리 목록 데이터 SSR 적용

---

package-lock.json
src/api/index.ts
src/components/Common/Image/Image.tsx
src/components/LectureDetail/CoachProfile/CoachProfile.tsx
src/components/Profile/Introduction/Introduction.tsx
src/components/Profile/LectureReview/LectureReview.tsx
src/components/Profile/LectureReview/LectureReviewStyle.ts
src/components/Profile/LectureReview/Review.tsx
src/components/Profile/ProfileHeader/ProfileHeader.tsx
src/hooks/profile/useCoachReview.ts
src/hooks/profile/useProfile.ts
src/pages/profile/[id].tsx
src/react-query/keys.ts
src/types/lectureDetail.ts
src/types/profile.ts

- #78
- userId를 받았을 때 해당 유저의 프로필을 받아오는 API 연동
- 리뷰 더 보기 버튼 구현
- 페이지 하나를 로딩하는데 2~5초씩 걸리는데 원인을 찾아봐야 할 것 같습니다..

#78 feat: 프로필 페이지 API 연동 

---

src/hooks/matching/useApplyMatching.ts

- #88
- matching form type 오타 수정
-

#88 modify: 매칭 신청서 페이지 배포 오류 수정

---

next.config.js
src/api/index.ts
src/components/CoachLecture/MatchingPopup/MatchingPopup.tsx
src/components/CoachLecture/MatchingPopup/MatchingPopupStyle.ts
src/components/CoachLecture/PlayerInfo/PlayerInfo.tsx
src/components/CoachLecture/PlayerInfo/PlayerInfoStyle.ts
src/components/CoachLecture/PlayerSchedule/PlayerSchedule.tsx
src/components/CoachLecture/PlayerSchedule/PlayerScheduleStyle.ts
src/components/CoachLecture/PlayerUser/PlayerUser.tsx
src/components/CoachLecture/PlayerUser/PlayerUserStyle.ts
src/components/CoachLecture/index.ts
src/components/Common/Image/Image.tsx
src/components/Home/LectureCard/LectureCard.tsx
src/hooks/coachLecture/useMatchingForm.ts
src/pages/coach-lecture/[id].tsx
src/react-query/keys.ts
src/types/coachLecture.ts
src/types/lectureInfo.ts
src/utils/formatSchedule.ts

- #83 
- 이미지 외부 url 도메인 변경 대응
- lectureinfo API 데이터 변경점 대응
- N/A

#83 feat: 최근 등록된 클래스 API 이미지값 변경 대응

---

src/pages/lecture-detail/[id].tsx
src/types/lectureDetail.ts

- #87
- 클래스 상세 페이지에서 오는 API category field가 변경되어 수정
-

#87 modify: 클래스 상세 페이지 API 변경 대응

---

src/hooks/profile/useProfile.ts
src/pages/review/index.tsx

#103 feat: 후기 작성 페이지 구조 수정

---

src/utils/formatSchedule.ts

- #106
- 10분보다 작은 경우 앞에 0을 붙였습니다.
-

#106 fix: 시간 포맷팅 00분 일 경우 예외처리

---

src/api/index.ts
src/hooks/review/useRegisterReview.ts
src/pages/review/index.tsx
src/types/index.d.ts

- #105
- 리뷰 작성 성공시에 안드로이드의 `showToast` 와 `navigateUp` 함수를 연결했습니다. 
-

#105 feat: 후기 작성 페이지 안드로이드 브릿지 연결

---

.storybook/main.js
.storybook/preview.js
package-lock.json
package.json
src/components/CoachLecture/MatchingPopup/MatchingPopup.tsx
src/components/Common/Button/ButtonStyle.ts
src/components/Common/Modal/Modal.stories.tsx
src/components/Common/Modal/Modal.tsx
src/components/Common/Modal/ModalStyle.ts
src/components/Common/index.ts
src/pages/coach-lecture/[id].tsx
src/styles/styles.d.ts
src/styles/theme.ts

- #91 
- Modal 컴포넌트 사용 시 문구는 `children` props로 추가해야 합니다.
- `buttonType === 'confirm'` => 확인 버튼 노출
- `buttonType !== 'confirm'` => 취소 버튼 및 buttonType 버튼 노출
- modal storybook 추가

#91 feat: Modal 공통 컴포넌트 추가

---

src/__tests__/category/LectureCategory.test.tsx
src/__tests__/category/useInfiniteLecture.test.tsx
src/components/Home/Category/Category.tsx
src/constants/categoryList.ts
src/mocks/handlers.js
src/mocks/mockData/lectureInfo.js
src/pages/lecture-category/[name].tsx

- #95
- 카테고리 별 클래스 목록 조회 시 categoryId -> categoryName으로 API 요청
- N/A

#95 feat: 카테고리 목록 조회 시 API 쿼리스트링 변경 대응

---

package-lock.json
src/components/LectureDetail/LectureInfo/LectureInfo.tsx

- #100
- 신청가능한 시간대가 없는 경우 예외 문구 설정했습니다.
-

#100 feat: 가능한 시간대가 없는 경우 예외처리

---

src/components/CoachLecture/PlayerSchedule/PlayerSchedule.tsx
src/components/CoachLecture/PlayerSchedule/PlayerScheduleStyle.ts
src/components/CoachLecture/PlayerUser/PlayerUser.tsx
src/pages/coach-lecture/[id].tsx
src/types/coachLecture.ts

- #102 
- 운영클래스 매칭신청서에 **플레이어가 보낸 일정** API 데이터 적용
- N/A

#102 feat: 운영클래스 매칭신청서 API 변경 대응

---

src/components/LectureDetail/MatchingButton/MatchingButton.tsx
src/components/LectureDetail/MatchingButton/MatchingButtonStyle.ts

- #77
- 유저의 볼이 0개인 경우 신청이 되지 않고 안내 모달이 뜨게 구현했습니다.
-

#77 feat: 유저가 볼이 없는 경우 모달 팝업

---

package-lock.json
package.json
src/components/Common/PageTransition/PageTransition.tsx
src/components/Common/index.ts
src/pages/matching/index.tsx

- #98
- `PageTransition`  이라는 공통 컴포넌트 작성
- 클래스->매칭신청서와  매칭신청서 단계 이동 할 때 애니메이션 효과 적용
- framer-motion 설치 했습니다!

#98 feat: 페이지 이동 애니메이션 추가

---

package-lock.json
src/components/Common/Header/HeaderStyle.ts
src/components/Common/SearchBar/SearchBarStyle.ts
src/components/Home/Category/CategoryStyle.ts

- #126
- 기획에 따라 카테고리 목록 반응형 뷰 적용
- N/A

#126 feat: 홈화면 카테고리 메뉴 여백 스타일 수정

---

src/components/LectureDetail/LectureInfo/LectureInfo.tsx

- #129
- 클래스 상세 페이지 사진 없는 경우 사진 영역 제거
-

#129 style: 클래스 상세 페이지 사진 없는 경우 사진 영역 제거

---

src/components/Home/Category/Category.tsx
src/components/Home/Category/CategoryStyle.ts
src/types/index.d.ts

- #139
- 홈화면에서 카테고리 아이템 메뉴 클릭 > 안드로이드 브릿지 연결 > 클래스 카테고리별 페이지로 이동
- N/A

#139 feat: 홈화면 > 카테고리 목록 페이지 이동 시 안드로이드 브릿지 연결

---

src/components/Profile/LectureReview/LectureReviewStyle.ts

- #135
- 후기가 없는 경우의 박스 width 제거
-

#135 style: 후기가 없는 경우의 박스의 설정된 width값 제거

---

src/components/Home/LectureCard/LectureCard.tsx
src/types/index.d.ts

- #150
- 홈화면->클래스 상세 브릿지 형태 수정
-

#150 fix: 홈화면 안드로이드 브릿지 수정

---

src/components/Matching/LastStep/LastStep.tsx

- #130
- 매칭 완료 후 버튼 클릭과 `navigateUp` 연결
-

#130 feat: 매칭신청서 안드로이드 브릿지 연결

---

src/components/Common/Forms/TextArea/TextAreaStyle.ts
src/components/Matching/ScheduleBox/ScheduleBoxStyle.ts
src/components/Matching/Title/TitleStyle.ts

- #147
- 각 상자의 고정된 width 값 제거했습니다.
-

#147 style: 매칭신청서 box width 제거

---

src/components/Profile/ProfileHeader/ProfileHeader.tsx

- #154
- 포트폴리오 링크에 http가 있는지 검증 하고 없다면 앞에 `https` 를 붙여 링크를 연결하도록 수정했습니다.
-

#154 fix: 마이페이지 링크 연결 안되는 오류 해결

---

src/pages/lecture-category/[name].tsx

- #131 
- 클래스 카테고리별 페이지 SSR -> ISR 렌더링 방식 수정
- N/A

#131 feat: 클래스 카테고리별 목록 데이터 응답 속도 개선

---

src/components/CoachLecture/FormDetail/PlayerSchedule/PlayerSchedule.tsx
src/components/CoachLecture/FormList/UserFormCard/UserFormCard.tsx
src/components/CoachLecture/FormList/UserFormCard/UserFormCardStyle.ts
src/components/CoachLecture/FormList/UserFormList/UserFormList.tsx
src/pages/coach-lecture/form-detail/[id].tsx

- #161 
- 매칭 신청인 목록 카드에 플레이어가 보낸 일정 (신청인이 가능한 시간) 정보 추가
- N/A

#161 feat: 운영클래스 매칭 신청인 가능한 시간 정보 추가

---

src/components/Profile/LectureReview/LectureReview.tsx
src/components/Profile/ProfileHeader/ProfileHeader.tsx
src/hooks/profile/useCoachReview.ts
src/hooks/profile/useProfile.ts
src/pages/profile/[id].tsx
src/pages/review/index.tsx

- #155
- 마이페이지에서 SSR로 데이터를 받아오는 것을 CSR로 수정했습니다.
- 유저의 리뷰를 받아오는 속도가 느려서 이 부분만 로딩화면 or 스켈레톤 ui로 처리하려고 합니다!

#155 feat: 마이페이지 SSR 제거

---

src/pages/profile/[id].tsx

- #172
- 프로필 페이지의 소개글을 `user.intro`로 수정
-

#172 fix: 마이페이지 소개글 오류 수정

---

src/pages/index.tsx

- #179 
- 최근 등록된 클래스 등록 후 홈화면 리빌딩 시 데이터 갱신 
- N/A

#179 feat: 홈화면 최근 등록된 클래스 렌더링 방식 수정

---

src/components/LectureDetail/CoachProfile/CoachProfile.tsx

- #181
-클래스 상세 페이지에서 프로필을 클릭했을 때 코치의 프로필 페이지로 라우팅 되게 구현했습니다.
-

#181 feat: 클래스 상세 페이지에서 프로필을 클릭했을 때 프로필 페이지로 라우팅

---

src/components/LectureDetail/CoachProfile/CoachProfile.tsx
src/components/LectureDetail/CoachProfile/CoachProfileStyle.ts

- #184
- 코치 프로필 사진 원형으로 수정
- 화면 크기가 달라져도 프로필 사진 크기가 일정하도록 수정
-

#184 style: 클래스 상세 페이지 코치 프로필 스타일 수정

---

src/components/LectureDetail/MatchingButton/MatchingButton.tsx

- #125
- 해당 클래스의 시간대가 없는 case 삭제
- 코치의 경우 버튼을 클릭했을 때 `navigateUp` 으로 안드로이드 브릿지 연결
-

#125 feat: 클래스 상세 페이지 안드로이드 브릿지 연결

---

Dockerfile

- #188
- Docker 파일 Node 버전 수정 -> `node:16.14.2-alpine`
- `COPY package-lock.json` -> `COPY yarn.lock` 으로 수정
- `nvm install 16.14.2`을 통해 명시된 노드 버전 관리 필요

#188 feat: Docker 파일 yarn berry에 맞게 설정 변경

---

Dockerfile

- #190 
- 도커 이미지 이름 `as BUILD`를 통해 강제 변경
- 이전에 설정되어 있었던 값 그대로 다시 추가했습니다.

#190 feat: 도커 이미지 이름 설정

---

.github/workflows/web-test-and-deploy-prod.yml
deployment/deployment-prod.yml

- resolves #192
- 프로덕션 환경 배포 파이프라인 작성
- 배포 파이프라인 작동 방법 : https://www.notion.so/sunsetmood/Github-Action-35277f962e5f4044b2b11f103d260c48
-

#192 feat: 프로덕션 배포 파이프라인 작성

---

packages/knowlly-webview/src/components/CoachLecture/FormDetail/Loading/Loading.tsx
packages/knowlly-webview/src/components/CoachLecture/FormDetail/Loading/LoadingStyle.ts
packages/knowlly-webview/src/components/CoachLecture/FormDetail/PlayerSchedule/PlayerSchedule.tsx
packages/knowlly-webview/src/components/CoachLecture/FormDetail/PlayerUser/PlayerUser.tsx
packages/knowlly-webview/src/components/CoachLecture/index.ts
packages/knowlly-webview/src/pages/coach-lecture/form-detail/[id].tsx

- #158
- 운영클래스 스켈레톤 UI 적용
- N/A

#158 feat: [웹뷰] 운영클래스 웹뷰 페이지 스켈레톤 UI 적용

---

packages/knowlly-landing/tsconfig.json
packages/knowlly-webview/tsconfig.json

- #212
- 웹뷰와 랜딩페이지가 컴파일 될 때 충돌이 일어나서 tsconfig 파일에 서로를 exclude 하는 옵션을 추가했습니다.
-

#212 chore: [웹뷰, 랜딩페이지] tsconfig exclude 옵션 추가

---

packages/knowlly-webview/src/components/LectureDetail/MatchingButton/MatchingButton.tsx
packages/knowlly-webview/src/pages/lecture-detail/[id].tsx

- #215
- `userId` 값이 하드코딩 되어있어 수정
-

#215 modify: [웹뷰] 하드코딩 되어있는 userId값 수정 
