YAPP-Github/20th-ALL-Rounder-Team-2-Web

src/components/ClassDetail/ClassInfo/ClassInfo.tsx
src/components/ClassDetail/CoachProfile/CoachProfile.tsx
src/components/ClassDetail/Guideline/Guideline.tsx
src/components/ClassDetail/Guideline/GuidelineStyle.ts
src/components/ClassDetail/HowToUse/HowToUse.tsx

- #36
<p align="center">
</p>
- 클래스 상세 페이지 텍스트 색상 수정
-

#36 style: 클래스 상세 페이지 텍스트 색상 수정

---

src/components/Common/Button/TextMore/TextMoreButton.tsx
src/components/Common/Button/TextMore/TextMoreButtonStyle.ts
src/components/Common/Typograpy/TypograpyStyle.ts
src/components/Profile/ClassReview/ClassReview.tsx
src/components/Profile/ClassReview/ClassReviewStyle.ts
src/components/Profile/ClassReview/Review.tsx
src/components/Profile/Introduction/Introduction.tsx
src/components/Profile/ProfileHeader/ProfileHeader.tsx
src/components/Profile/ProfileHeader/ProfileHeaderStyle.ts
src/components/Profile/index.ts
src/pages/profile/[id].tsx

- #16
- 코치일 때 프로필 상세 페이지 레이아웃 생성
- 텍스트 더보기의 경우 110자를 기준으로 설정
- 텍스트 스타일 subtitle-4의 폰트 설정이 달라 수정했습니다.

#16 feat: 코치 프로필 상세 페이지 레이아웃

---

.github/workflows/web-test-and-deploy-dev.yml
deployment/deployment-dev.yml

- #43 
- develop 브랜치가 push 될때마다, 테스트 서버에 배포되도록 github workflow 작성
- 테스트 웹 서버 URL : http://knowllydev-web.hkpark.net/
- Repository Secret에 각각 아래의 시크릿 값 추가
- `DOCKER_USERNAME` : dockerhub 이름
- `DOCKER_PASSWORD` : dockerhub 비밀번호
- `KUBE_CONFIG_DATA_DEV` : 쿠버네티스 배포 설정값
- Repository Secret의 `DOCKER_USERNAME`, `DOCKER_PASSWORD` 는 임의로 제 것으로 해두었으나, 본인 것으로 대체하셔도 됩니다.
- 단, `KUBE_CONFIG_DATA_DEV`는 건들면 안됩니다!
- 이후 Dockerfile의 스크립트 최적화가 필요합니다. #45 
- 현재 Dockfile의 Entrypoint가 개발용 명령어인 `npm run dev` 으로 되어있는데, 이는 개발용 도구 때문에 배포 환경에서는 맞지 않습니다. (리소스 이슈)
- `npm run build` 후 serve 하는 방향으로. static하게 동작하도록 수정 요청 드립니다. ([관련 링크](https://appdevelopmaster.tistory.com/506))

#43 feat: 테스트 서버 배포 워크플로우 추가

---

src/components/Home/LectureCard/LectureCard.tsx
src/components/Home/LectureCard/LectureCardStyle.ts
src/types/lectureInfo.ts

- #73 
- 최근 등록된 클래스 목록, 카테고리 클래스 목록, 검색된 클래스 목록 등에서 클래스 클릭 시 클래스 상세 페이지로 이동
- 상세 페이지에 대한 데이터 prefetch를 위해 next/link 사용
- N/A

#73 feat: 등록된 클래스 목록에서 상세페이지로 라우팅 연결

---

src/api/index.ts
src/components/Matching/FirstStep/FirstStep.tsx
src/components/Matching/ScheduleBox/ScheduleBox.tsx
src/components/Matching/SecondStep/SecondStep.tsx
src/hooks/matching/useApplyMatching.ts
src/pages/matching/index.tsx
src/recoil/matching/atoms.ts
src/types/matching.ts

- #72
(아직 API 변한거 적용을 안했더니 카테고리가 안뜨네요 ,, )
- 유저가 클래스에 매칭을 신청할 수 있는 기능 구현
- `playerMatching`이라는 recoil state가 불필요해보여 추후 리팩토링을 하면서 수정을 할 예정입니다.
- 페이지를 부드럽게 이동하는 애니메이션 적용이 필요해보입니다.

#72 feat: 매칭 신청서 작성 기능 구현

---

src/api/index.ts
src/components/CoachLecture/MatchingPopup/MatchingPopup.tsx
src/components/CoachLecture/MatchingPopup/MatchingPopupStyle.ts
src/components/CoachLecture/PlayerInfo/PlayerInfo.tsx
src/components/CoachLecture/PlayerInfo/PlayerInfoStyle.ts
src/components/CoachLecture/PlayerSchedule/PlayerSchedule.tsx
src/components/CoachLecture/PlayerSchedule/PlayerScheduleStyle.ts
src/components/CoachLecture/PlayerUser/PlayerUser.tsx
src/components/CoachLecture/PlayerUser/PlayerUserStyle.ts
src/components/CoachLecture/index.ts
src/components/Common/Image/Image.tsx
src/hooks/coachLecture/useMatchingForm.ts
src/pages/coach-lecture/[id].tsx
src/react-query/keys.ts
src/types/coachLecture.ts
src/utils/formatSchedule.ts

- #81 
- 플레이어가 보낸 일정 추후 API 변경에 따라 대응 예정
- N/A
- Image 컴포넌트에 type `coach-profile` 추가
- formatDate 유틸 함수 type 매개변수 추가

#81 feat: 운영클래스 매칭 신청인의 매칭 신청서 페이지 구현

---

src/components/LectureDetail/CoachProfile/CoachProfile.tsx
src/components/Matching/FirstStep/FirstStep.tsx
src/hooks/lecture/useLectureDetail.ts
src/pages/matching/index.tsx

- #88
- 매칭신청서 새로고침 시 undefined 뜨는 오류 수정
-  매칭신청서 페이지에서 새로고침을 하게 되면 클래스 상세 페이지에서 받은 query가 inactive 상태로 바뀝니다. SSR로 해결하긴 했는데 혹시 더 좋은 방법 생각나시면 추천 부탁드립니다 ..

#88 매칭 신청서 페이지 배포 오류 수정 

---

src/components/LectureDetail/MatchingButton/MatchingButton.tsx

- #107
- 매칭되지 않았을 때 빈 배열이 리턴될 수 있으므로 null에 대한 id 접근하는 경우 예외처리 했습니다.
- 지금 그래도 id가 3인 클래스에 대해 오류가 뜨는데, `matched` 가 `true` 인데 불구하고 `matchedUser`가 `null`로 설정되어 있어서 그런 것 같습니다.
-

#107 fix: 클래스 상세 페이지 매칭된 사람이 없는 경우 예외처리

---

src/components/Common/Header/Header.tsx

- #115 
- 검색 페이지에서 헤더 뒤로가기 버튼 누를 경우 브릿지 연결을 통해 홈 화면으로 이동
- N/A

#115 feat: 검색 페이지 뒤로가기 버튼 브릿지 연결

---

src/components/Home/EmptyLectureList/EmptyLectureList.tsx

- #127 
- 검색 페이지 검색 후 결과 없음 버튼 노출 > 클릭 후 안드로이드 브릿지 연결(navigateUp) > 홈화면으로 이동
- N/A

#127 feat: 검색 페이지 검색 결과 없음 > 홈으로 가기 버튼에 안드로이드 브릿지 연결

---

src/components/Common/Forms/TextArea/TextArea.tsx
src/components/Matching/SecondStep/SecondStep.tsx
src/components/Matching/SecondStep/SecondStepStyle.ts

- #128
- 키보드에 onFocus 이벤트가 발생하면 버튼의 속성에 `display: none`을 주어 해결했습니다.
-

#128 feat: 매칭 신청서 키보드가 버튼이랑 같이 올라오는 버그

---

src/components/LectureDetail/MatchingButton/MatchingButton.tsx
src/components/LectureDetail/MatchingButton/MatchingButtonStyle.ts

- #122
- 클래스 상세 페이지에서 화면 크기에 상관 없이 버튼이 가운데 정렬이 될 수 있게끔 수정
-

#122 feat: 클래스 상세페이지 CTA 버튼 가운데 정렬

---

src/components/Matching/LastStep/LastStep.tsx
src/components/Matching/LastStep/LastStepStyle.ts
src/components/Matching/SecondStep/SecondStep.tsx
src/components/Matching/SecondStep/SecondStepStyle.ts

- #145
- 화면 크기에 따라 이미지가 잘려보이는 문제가 있어 background-image로 변경했습니다.
- 매칭 완료 버튼도 화면 크기에 상관 없이 가운데 정렬되게 수정했습니다.
-

#145 feat: 매칭 신청 완료 후 보이는 이미지를 background-image 속성으로 수정

---

src/components/Matching/SecondStep/SecondStep.tsx

- #148
- 이전에는 focus, blur 이벤트에 대해 `display`를 지정해줬는데 키보드가 닫혀도 `focus` 상태인 경우의 문제점이 있었습니다.
- 그래서 아예 `viewPort`의 `innerHeight`를 계산해서 화면의 절반 이하이면 키보드가 열려있다고 판단하여 `display:none`을 주었습니다. 
- 이제 `focus` 상태여도 키보드가 닫혀있으면 버튼이 보여요~!~!~!!
-

#148 fix: 매칭신청서 키보드가 열렸을 때 버튼이 화면 위로 올라오는 문제 해결

---

src/components/LectureDetail/MatchingButton/MatchingButton.tsx
src/hooks/lecture/useLectureDetail.ts
src/pages/lecture-detail/[id].tsx
src/pages/matching/index.tsx

- #138
- 기존의 SSR에서 CSR로 바꿔 2~3초 걸리던 렌더링을 50ms로 줄였습니다. 🥺
- 안드로이드에서 스피너가 적용된걸로 알아서 일단 `isFetching`일 때 화면을 고려하지 않았습니다!

#138 feat: 클래스 상세 페이지 렌더링 속도 개선

---

src/components/Profile/LectureReview/Review.tsx

- #167
- 프로필 페이지에서 사용자의 리뷰를 보여주는 부분의 프로필이 하드 코딩되어 있어 수정했습니다.
-

#167 modify: 사용자 리뷰 프로필 사진 하드코딩 되어있는 부분 수정

---

src/components/Home/LectureCard/LoadingCardStyle.ts
src/components/Profile/LectureReview/LectureReview.tsx
src/components/Profile/LectureReview/LoadingReview.tsx
src/components/Profile/LectureReview/LoadingReviewStyle.ts

- #164
- 프로필 페이지에서 리뷰 api가 더 늦게 로딩되어 해당 부분만 skeleton UI 적용했습니다.
-

#164 feat: 프로필 페이지 skeleton UI 적용

---

src/api/index.ts
src/components/CoachLecture/FormDetail/MatchingPopup/MatchingPopup.tsx
src/components/CoachLecture/FormDetail/PlayerUser/PlayerUser.tsx
src/hooks/coachLecture/useMatchingForm.ts
src/hooks/coachLecture/usePatchFormState.ts
src/pages/coach-lecture/form-detail/[id].tsx
src/types/coachLecture.ts

- #159 
- 매칭 신청서 거절/수락 버튼 클릭 > API 요청 > 안드로이드 브릿지 연결(토스트 팝업)
- ~~거절/수락 후 운영 클래스 매칭 중 페이지로 이동하는 안드로이드 브릿지 연결 예정 - PR Draft 상태~~
- 거절/수락 API 요청 후  성공 시 매칭 중 웹뷰 종료 브릿지(navigateUp) 연결 완료

#159 feat: 운영클래스 매칭 신청서 거절/수락 시 안드로이드 브릿지 연결

---

src/utils/formatSchedule.ts

- #178
- 오후에 시작해 새벽에 끝나는 클래스의 경우 음수로 계산되는 경우가 있어 해당 경우가 나오지 않도록 처리했습니다.
-

#178 feat: 클래스 시간 음수로 뜨는 오류 수정 

---

Dockerfile
packages/knowlly-landing/package.json

- #195
- 배포 시 발생했던 도커 파일 오류 (아래 사진 첨부) 해결
- 도커 멀티 스테이지 추가로 오류 해결
- 위 오류를 해결하니 빌드에서 오류 발생
```
=> ERROR [build 12/12] RUN yarn webview build                                                                                                                                         20.5s
------                                                                                                                                                                                       
> [build 12/12] RUN yarn webview build: 
// ...생략
#17 19.43 info  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled
#17 19.95 error - Failed to load SWC binary for linux/arm64, see more info here: …
```

#195 feat: yarnberry를 통한 도커 이미지 빌드 시 에러 이슈 해결

---

packages/knowlly-landing/src/components/Footer/Footer.tsx
packages/knowlly-landing/src/components/Footer/FooterStyle.ts
packages/knowlly-landing/src/pages/index.tsx
packages/knowlly-landing/src/styles/theme.ts
packages/knowlly-landing/tsconfig.json

- #196
- 랜딩페이지 footer component 구현
- 폰트나 스타일을 공통으로 관리하고 싶은데 common-styles에 theme.ts 파일을 만들면 읽을 수 있는 loader가 없다는 오류가 뜨네요..ㅠ 일단 어떻게 해결해야할지 몰라서 개별 theme.ts 파일을 작성했습니다.

#196 feat: [랜딩페이지] Footer 구현
